version: '3'

services:
  jupyter:
    build: .
    image: jupyter:latest
    container_name: ih-data-powerbi
    working_dir: /app/jupyter
    command: jupyter notebook --ip 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8888:8888"
  postgres:
    image: postgis/postgis:15-master
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
