version: '3'

services:
  jupyter:
    build:
      context: ./jupyter
    container_name: ih-data-powerbi
    working_dir: /app/jupyter
    command: jupyter notebook --ip 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    links:
      - postgres
  postgres:
    image: postgis/postgis
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
